### Create new task
POST http://localhost:8080/tasks
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlbGlzYUBleGFtcGxlLmNvbSIsImlzcyI6IlRPRE9fVEFTS1MiLCJpZCI6ImVsaXNhQGV4YW1wbGUuY29tIiwiZXhwIjoxNjc4NzY0MzI1fQ.Grf6H7itXDz8eEI7opipI96f7Sq0FoSE_xzNV1lm-Tm1b7Zg-pJmFetFje6WQv5dWCPUvZsQTQ-i_rz3YVi6IA

{
  "title": "Simple task 1",
  "description": "Simple task description 1",
  "dueDate": "2023-05-01T09:18:27Z",
  "status": "TODO"
}

### Filtering task. Could receive parameters id, title, description, and status
GET http://localhost:8080/tasks?id=6d405dcb-76c8-46a1-982b-089e43fa3591
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlbGlzYUBleGFtcGxlLmNvbSIsImlzcyI6IlRPRE9fVEFTS1MiLCJpZCI6ImVsaXNhQGV4YW1wbGUuY29tIiwiZXhwIjoxNjc4NzY0MzI1fQ.Grf6H7itXDz8eEI7opipI96f7Sq0FoSE_xzNV1lm-Tm1b7Zg-pJmFetFje6WQv5dWCPUvZsQTQ-i_rz3YVi6IA

### Update existent task
PUT http://localhost:8080/tasks/6d405dcb-76c8-46a1-982b-089e43fa3591
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlbGlzYUBleGFtcGxlLmNvbSIsImlzcyI6IlRPRE9fVEFTS1MiLCJpZCI6ImVsaXNhQGV4YW1wbGUuY29tIiwiZXhwIjoxNjc4NzY0MzI1fQ.Grf6H7itXDz8eEI7opipI96f7Sq0FoSE_xzNV1lm-Tm1b7Zg-pJmFetFje6WQv5dWCPUvZsQTQ-i_rz3YVi6IA

{
  "title": "Ler um capitulo do livro Hobbit",
  "description": "Ler o capítulo 5 do livro \"O Hobbit\"",
  "dueDate": "2023-12-25T10:30:00Z",
  "status": "IN_PROGRESS"
}

### Remove task
DELETE http://localhost:8080/tasks/6d405dcb-76c8-46a1-982b-089e43fa3591
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlbGlzYUBleGFtcGxlLmNvbSIsImlzcyI6IlRPRE9fVEFTS1MiLCJpZCI6ImVsaXNhQGV4YW1wbGUuY29tIiwiZXhwIjoxNjc4NzY0MzI1fQ.Grf6H7itXDz8eEI7opipI96f7Sq0FoSE_xzNV1lm-Tm1b7Zg-pJmFetFje6WQv5dWCPUvZsQTQ-i_rz3YVi6IA